@startuml

package Robot{
	class ActorUnit{
		- actionSender : ActionSender
		+ Act(LowLevelActionOpetration)
	}
	class SensorUnit{
		+ getSensorData()
	}
}

package EvaluationSystem{
	class Env{
		- sensorUnit : SensorUnit
		- envData : float
		+ GetEnvData() : float
	}
	abstract AbstractEvaluation{
		- env : Env
		- evaluationResult : Result
		+ EvaluateEnvironment(Env) : Result
	}
	class ConcleteEvaluation{
		+ ConcleteEvaluateEnvironment(Env) : Result
	}
	abstract Result
	class EvaluationResult
}

SensorUnit --> Env : 環境データを送信
Env --> AbstractEvaluation : 評価したいデータを送信
AbstractEvaluation <-- Result : 評価結果のフォーマットを定義
AbstractEvaluation <|-- ConcleteEvaluation : 実装
Result <|-- EvaluationResult : 実装


package ActionDecisionSystem{
	class Operator{
		- evaluation : AbstractEvaluation
		- result : Result
	}
	struct Action
	class ActionSender{
		+ SendAction(Action)
	}
}

AbstractEvaluation --> Operator : 評価結果を送信
Action --> Operator : ActorUnitに送信するアクションのフォーマットを定義
Operator --> ActionSender : 決定されたアクションデータを送信
ActionSender --> ActorUnit : 低レイヤーの行動命令を送信

@enduml