@startuml クラス図
package Robot {
	class Agent {
		- motionUnitInfo: MotionUnitInfo
		- sensorUnitInfo: SensorUnitInfo
		+ getMotionUnitInfo(): MotionUnitInfo
		+ getSensorUnitInfo(): SensorUnitInfo
	}
	class MotionUnit {
		+ モーション実行(motion: AgentMotion)
	}
	class SensorUnit {
		+ センサ情報を取得(): SensorData
	}
}

package ManagementSystem {
	class SensorInfoReceiver {
		- 整形済みセンサ情報: FormattedSensorInfo
		+ データ受け取り(data: SensorData)
		+ getEnvData(): FormattedSensorInfo
	}
	class EnvAssessor {
		- environmentData: EnvironmentData
		+ assessEnvironment(data: FormattedSensorInfo): Assessment
	}
	class BehaviorSelector {
		+ selectBehavior(assessment: Assessment): Behavior
	}
	class Environment {
		- assessments: List<Assessment>
		- behaviors: List<Behavior>
		+ getAssessmentForCondition(condition: EnvironmentCondition): Assessment
		+ getBehaviorForAssessment(assessment: Assessment): Behavior
	}
	class RobotOperator {
		+ generateMotion(behavior: Behavior): AgentMotion
	}
	class AgentMotion
	class Behavior
	class Assessment
}

Agent "1" o-- "1" MotionUnit
Agent "1" o-- "1" SensorUnit

Agent "*" -right-> "1" SensorInfoReceiver : センサ情報を送信

SensorInfoReceiver "1" --> "1" EnvAssessor : 整形済みセンサ情報を送信
EnvAssessor "1" --> "1" BehaviorSelector : 環境評価を送信
BehaviorSelector "1" --> "1" RobotOperator : 評価のもと振る舞い送信
EnvAssessor "1" --> "*" Environment : assessmentsを参照
BehaviorSelector "1" --> "*" Environment : behaviorsを参照
Environment "1" *-- "*" Assessment
Environment "1" *-- "*" Behavior
RobotOperator "1" o-- "*" AgentMotion : 所持
Agent "*" <-right- "1" RobotOperator : 具体的な動作を送信

@enduml