@startuml Evaluate
skinparam Linetype ortho

abstract SensorUnit
abstract Environment
abstract Observer
class ConcleteEnvironment
class ConcleteObserver

SensorUnit <- Environment
Environment <- Observer
Environment <|-- ConcleteEnvironment
Observer <|-- ConcleteObserver
ConcleteEnvironment <- ConcleteObserver

@enduml