@startuml overview
skinparam Linetype ortho

abstract Sensor{
	- SensorInfo info
	+ Update(): void
	+ GetSensorInfo(): SensorInfo
}
class M5StickC{
	+ Update() : void
	- デシリアライズ() : void
}
class SerialHundler{
	+ Update() : void
	- シリアル通信() : void
}
class DummySensor{
	+ Update() : void
	- ダミーデータ生成 : void
}
struct SensorInfo{
	string deviceName
	float[] acceleration
	float[] gyro
	float temp
	float humidity
	float battery
}
abstract Evaluate{
	+ EvaluateEnvironment() : Result
}
class ConcleteEvaluate{

}
abstract Result
class ConcleteResult

class Toio

Sensor <-right- Evaluate
Sensor <|-- M5StickC
Sensor <|-- DummySensor
Sensor *-- SensorInfo
M5StickC o-- SerialHundler
Evaluate -right- Result
Evaluate <|-down-ConcleteEvaluate
Result <|-down- ConcleteResult
ConcleteEvaluate -right- ConcleteResult
@enduml